Repository grpc/grpc-dart, pull requests merged in 2020-09, with the labels that each got.

#351 Revert "Support grpc-web in pure dart (#287)"
  lib/src/client/transport/xhr_transport.dart
  test/client_tests/client_xhr_transport_test.dart
Labels: P0

#352 Regenerate certificates used by tests.
  test/data/README.md
  test/data/certstore.p12
  test/data/localhost.crt
  test/data/localhost.key
Labels: size/S

#353 Remove check for SecurityContext.alpnSupported in security#createSecurityContext
  lib/src/shared/security.dart
Labels: size/XS

#355 Prepare to publish 2.2.0+2
  CHANGELOG.md
  pubspec.yaml
Labels: size/XS

#359 Fix for Windows Travis builds
  .travis.yml
Labels: size/S

#347 Add browser features to Dart gRPC-web for parity with JS implementation.
  CHANGELOG.md
  lib/grpc_web.dart
  lib/src/client/call.dart
  lib/src/client/connection.dart
  lib/src/client/http2_connection.dart
  lib/src/client/query_parameter.dart
  lib/src/client/transport/cors.dart
  lib/src/client/transport/xhr_transport.dart
  pubspec.yaml
  test/client_tests/client_xhr_transport_test.dart
Labels: size/L

#360 Beef up exception handling in gRPC code.
  CHANGELOG.md
  lib/src/client/call.dart
  lib/src/client/transport/transport.dart
  lib/src/client/transport/xhr_transport.dart
  pubspec.yaml
  test/client_tests/client_test.dart
  test/client_tests/client_xhr_transport_test.dart
  test/src/client_utils.dart
Labels: size/L

#363 Add client validation to server credentials
  CHANGELOG.md
  lib/grpc.dart
  lib/service_api.dart
  lib/src/server/server.dart
  pubspec.yaml
Labels: size/M
