Repository grpc/grpc-dart, pull requests merged in 2020-10, with the labels that each got.

#366 Revert "Not to fail pending requests, just reschedule it (#303)"
  lib/src/client/http2_connection.dart
  test/client_tests/client_test.dart
Labels: size/S

#364 Create gRPC servers and clients with TransportConnections.
  CHANGELOG.md
  lib/grpc.dart
  lib/src/client/client_transport_connector.dart
  lib/src/client/http2_channel.dart
  lib/src/client/http2_connection.dart
  lib/src/server/server.dart
  pubspec.yaml
  test/client_tests/client_transport_connector_test.dart
  test/connection_server_test.dart
  test/src/client_utils.dart
  test/src/server_utils.dart
Labels: size/XXL

#370 Revert "Fix for Windows Travis builds"
  .travis.yml
Labels: size/S

#358 Remove unused dart:async imports
  lib/src/auth/auth_io.dart
  lib/src/client/client.dart
  lib/src/client/connection.dart
Labels: size/XS

#354 Add a simple end-to-end gRPC-web test
  .travis.yml
  CONTRIBUTING.md
  pubspec.yaml
  test/grpc_web_server.dart
  test/grpc_web_test.dart
  test/src/generated/echo.pb.dart
  test/src/generated/echo.pbenum.dart
  test/src/generated/echo.pbgrpc.dart
  test/src/generated/echo.pbjson.dart
  test/src/protos/echo.proto
  tool/install-grpcwebproxy.sh
Labels: size/XL

#342 Call to onMetadata handles exceptions
  lib/src/server/handler.dart
  test/round_trip_test.dart
Labels: size/M

#376 Propagate cancellation from responses stream to the call
  lib/src/client/call.dart
  test/round_trip_test.dart
Labels: size/M

#212 Don't print from server
  lib/src/server/server.dart
Labels: cla: yes, size/S

#377 Bump SDK constraint and add dependency on fixnum
  CHANGELOG.md
  pubspec.yaml
Labels: size/S
