Repository grpc/grpc-dart, pull requests merged in 2020-12, with the labels that each got.

#407 Add weekly cron to GitHub workflow
  .github/workflows/dart.yml
Labels: size/XS

#409 Support message compression
  CHANGELOG.md
  example/helloworld/bin/client.dart
  example/helloworld/bin/server.dart
  lib/grpc.dart
  lib/src/client/call.dart
  lib/src/client/http2_connection.dart
  lib/src/client/options.dart
  lib/src/client/transport/http2_transport.dart
  lib/src/server/handler.dart
  lib/src/server/server.dart
  lib/src/shared/codec.dart
  lib/src/shared/codec_registry.dart
  lib/src/shared/message.dart
  pubspec.yaml
  test/client_tests/client_test.dart
  test/round_trip_test.dart
  test/shared_tests/codec_registry_test.dart
  test/src/client_utils.dart
  test/src/server_utils.dart
  test/src/utils.dart
Labels: size/L

#415 Avoid deprecated List() constructor.
  analysis_options.yaml
  lib/src/client/transport/xhr_transport.dart
  test/client_tests/client_interceptor_test.dart
Labels: size/XS

#414 Prevent an exception to be thrown when a web connection stream is closed
  lib/src/client/transport/xhr_transport.dart
  test/grpc_web_test.dart
Labels: size/S
