Repository grpc/grpc-dart, pull requests merged in 2020-11, with the labels that each got.

#338 feat: support client interceptors
  lib/grpc.dart
  lib/service_api.dart
  lib/src/client/client.dart
  lib/src/client/common.dart
  lib/src/client/interceptor.dart
  test/client_handles_bad_connections_test.dart
  test/client_tests/client_interceptor_test.dart
  test/round_trip_test.dart
  test/server_handles_broken_connection_test.dart
  test/src/client_utils.dart
Labels: size/L

#378 Update pubspec.yaml, CHANGELOG.md and expand deprecation notice
  CHANGELOG.md
  lib/src/client/client.dart
  pubspec.yaml
  test/grpc_web_server.dart
Labels: size/S

#383 Create dart.yml
  .github/workflows/dart.yml
Labels: size/M

#387 Update dart.yml
  .github/workflows/dart.yml
  analysis_options.yaml
  example/helloworld/lib/src/generated/helloworld.pb.dart
  example/helloworld/lib/src/generated/helloworld.pbenum.dart
  example/helloworld/lib/src/generated/helloworld.pbjson.dart
  example/route_guide/lib/src/generated/route_guide.pb.dart
  example/route_guide/lib/src/generated/route_guide.pbenum.dart
  example/route_guide/lib/src/generated/route_guide.pbjson.dart
  test/src/generated/echo.pb.dart
  test/src/generated/echo.pbenum.dart
  test/src/generated/echo.pbjson.dart
Labels: size/L

#389 Update dart.yml: Add matrix for 'analyze' job
  .github/workflows/dart.yml
Labels: size/XS

#388 Update README.md
  README.md
Labels: size/XS

#390 Enable Web tests and make sure to install right channel
  .github/workflows/dart.yml
  tool/install-grpcwebproxy.sh
Labels: size/M

#393 Remove Travis
  .travis.yml
  README.md
Labels: size/M

#391 Fix badge in readme
  README.md
Labels: size/XS

#327 Add support for unix domain sockets
  CHANGELOG.md
  README.md
  example/helloworld/README.md
  example/helloworld/bin/unix_client.dart
  example/helloworld/bin/unix_server.dart
  example/helloworld/pubspec.yaml
  interop/pubspec.yaml
  lib/src/client/http2_channel.dart
  lib/src/client/http2_connection.dart
  lib/src/server/server.dart
  pubspec.yaml
  test/client_handles_bad_connections_test.dart
  test/common.dart
  test/round_trip_test.dart
  test/server_handles_broken_connection_test.dart
Labels: size/L

#372 Ensure CallOptions merge preserves Web specific options
  lib/src/client/call.dart
  test/client_tests/call_test.dart
Labels: size/M

#392 Add timeline logging to grpc client
  lib/grpc.dart
  lib/grpc_web.dart
  lib/src/client/call.dart
  lib/src/client/channel.dart
  lib/src/shared/profiler.dart
  test/timeline_test.dart
Labels: cla: yes, size/L

#397 Fix for duplicate headers
  .github/workflows/dart.yml
  CHANGELOG.md
  CONTRIBUTING.md
  lib/src/client/transport/xhr_transport.dart
  test/grpc_web_server.dart
  test/grpc_web_test.dart
  tool/install-grpcwebproxy.sh
Labels: size/L

#332 Fix concurrent modification error in GrpcWebClientChannel.terminate
  CHANGELOG.md
  lib/src/client/transport/xhr_transport.dart
  test/grpc_web_test.dart
Labels: size/L

#399 Release 2.8.0
  CHANGELOG.md
  pubspec.yaml
Labels: size/XS
