Repository grpc/grpc-dart, pull requests merged in 2021-03, with the labels that each got.

#454 Avoid completing multiple times for one error
  .github/workflows/dart.yml
  CHANGELOG.md
  interop/lib/src/client.dart
  pubspec.yaml
Labels: size/S

#455 Require latest googleapis_auth to avoid deprecated API usage
  CHANGELOG.md
  lib/src/auth/auth.dart
  pubspec.yaml
Labels: size/XS

#460 Be more resilient to broken deployments
  CHANGELOG.md
  lib/src/client/call.dart
  lib/src/client/transport/http2_transport.dart
  lib/src/client/transport/xhr_transport.dart
  lib/src/shared/status.dart
  lib/src/shared/streams.dart
  test/client_tests/client_test.dart
  test/client_tests/client_transport_connector_test.dart
  test/client_tests/client_xhr_transport_test.dart
  test/grpc_web_server.dart
  test/grpc_web_test.dart
  test/src/client_utils.dart
  test/stream_test.dart
Labels: size/XL
