Repository grpc/grpc-dart, pull requests merged in 2021-02, with the labels that each got.

#444 Regenerate proto code with latest generator
  example/googleapis/lib/src/generated/google/api/label.pb.dart
  example/googleapis/lib/src/generated/google/api/label.pbenum.dart
  example/googleapis/lib/src/generated/google/api/label.pbjson.dart
  example/googleapis/lib/src/generated/google/api/launch_stage.pb.dart
  example/googleapis/lib/src/generated/google/api/launch_stage.pbenum.dart
  example/googleapis/lib/src/generated/google/api/launch_stage.pbjson.dart
  example/googleapis/lib/src/generated/google/api/monitored_resource.pb.dart
  example/googleapis/lib/src/generated/google/api/monitored_resource.pbenum.dart
  example/googleapis/lib/src/generated/google/api/monitored_resource.pbjson.dart
  example/googleapis/lib/src/generated/google/logging/type/http_request.pb.dart
  example/googleapis/lib/src/generated/google/logging/type/http_request.pbenum.dart
  example/googleapis/lib/src/generated/google/logging/type/http_request.pbjson.dart
  example/googleapis/lib/src/generated/google/logging/type/log_severity.pb.dart
  example/googleapis/lib/src/generated/google/logging/type/log_severity.pbenum.dart
  example/googleapis/lib/src/generated/google/logging/type/log_severity.pbjson.dart
  example/googleapis/lib/src/generated/google/logging/v2/log_entry.pb.dart
  example/googleapis/lib/src/generated/google/logging/v2/log_entry.pbenum.dart
  example/googleapis/lib/src/generated/google/logging/v2/log_entry.pbjson.dart
  example/googleapis/lib/src/generated/google/logging/v2/logging.pb.dart
  example/googleapis/lib/src/generated/google/logging/v2/logging.pbenum.dart
  example/googleapis/lib/src/generated/google/logging/v2/logging.pbgrpc.dart
  example/googleapis/lib/src/generated/google/logging/v2/logging.pbjson.dart
  example/googleapis/lib/src/generated/google/protobuf/any.pb.dart
  example/googleapis/lib/src/generated/google/protobuf/any.pbenum.dart
  example/googleapis/lib/src/generated/google/protobuf/any.pbjson.dart
  example/googleapis/lib/src/generated/google/protobuf/duration.pb.dart
  example/googleapis/lib/src/generated/google/protobuf/duration.pbenum.dart
  example/googleapis/lib/src/generated/google/protobuf/duration.pbjson.dart
  example/googleapis/lib/src/generated/google/protobuf/empty.pb.dart
  example/googleapis/lib/src/generated/google/protobuf/empty.pbenum.dart
  example/googleapis/lib/src/generated/google/protobuf/empty.pbjson.dart
  example/googleapis/lib/src/generated/google/protobuf/struct.pb.dart
  example/googleapis/lib/src/generated/google/protobuf/struct.pbenum.dart
  example/googleapis/lib/src/generated/google/protobuf/struct.pbjson.dart
  example/googleapis/lib/src/generated/google/protobuf/timestamp.pb.dart
  example/googleapis/lib/src/generated/google/protobuf/timestamp.pbenum.dart
  example/googleapis/lib/src/generated/google/protobuf/timestamp.pbjson.dart
  example/googleapis/lib/src/generated/google/rpc/status.pb.dart
  example/googleapis/lib/src/generated/google/rpc/status.pbenum.dart
  example/googleapis/lib/src/generated/google/rpc/status.pbjson.dart
  example/grpc-web/lib/src/generated/echo.pb.dart
  example/grpc-web/lib/src/generated/echo.pbenum.dart
  example/grpc-web/lib/src/generated/echo.pbgrpc.dart
  example/grpc-web/lib/src/generated/echo.pbjson.dart
  example/helloworld/lib/src/generated/helloworld.pb.dart
  example/helloworld/lib/src/generated/helloworld.pbenum.dart
  example/helloworld/lib/src/generated/helloworld.pbgrpc.dart
  example/helloworld/lib/src/generated/helloworld.pbjson.dart
  example/metadata/README.md
  example/metadata/lib/src/generated/metadata.pb.dart
  example/metadata/lib/src/generated/metadata.pbgrpc.dart
  example/route_guide/lib/src/generated/route_guide.pb.dart
  example/route_guide/lib/src/generated/route_guide.pbenum.dart
  example/route_guide/lib/src/generated/route_guide.pbgrpc.dart
  example/route_guide/lib/src/generated/route_guide.pbjson.dart
  interop/lib/src/generated/empty.pb.dart
  interop/lib/src/generated/messages.pb.dart
  interop/lib/src/generated/messages.pbenum.dart
  interop/lib/src/generated/test.pb.dart
  interop/lib/src/generated/test.pbgrpc.dart
Labels: size/XXL

#446 Fix grpc-web example, update documentation
  example/grpc-web/README.md
  example/grpc-web/pubspec.yaml
Labels: size/S

#445 Enable and fix pedantic v1.9 lints
  .github/workflows/dart.yml
  analysis_options.yaml
  example/grpc-web/lib/app.dart
  example/metadata/bin/client.dart
  example/metadata/bin/server.dart
  example/metadata/lib/src/client.dart
  example/metadata/lib/src/server.dart
  example/route_guide/bin/client.dart
  example/route_guide/bin/server.dart
  example/route_guide/lib/src/client.dart
  example/route_guide/lib/src/server.dart
  interop/lib/src/client.dart
  lib/src/auth/auth.dart
  lib/src/auth/auth_io.dart
  lib/src/auth/rsa.dart
  lib/src/client/call.dart
  lib/src/client/client.dart
  lib/src/client/common.dart
  lib/src/client/http2_connection.dart
  lib/src/client/options.dart
  lib/src/client/transport/http2_credentials.dart
  lib/src/client/transport/http2_transport.dart
  lib/src/client/transport/transport.dart
  lib/src/client/transport/xhr_transport.dart
  lib/src/server/handler.dart
  lib/src/server/server.dart
  lib/src/server/service.dart
  lib/src/shared/codec.dart
  lib/src/shared/profiler.dart
  test/client_handles_bad_connections_test.dart
  test/client_tests/call_test.dart
  test/client_tests/client_interceptor_test.dart
  test/client_tests/client_test.dart
  test/client_tests/client_transport_connector_test.dart
  test/client_tests/client_xhr_transport_test.dart
  test/connection_server_test.dart
  test/grpc_web_decoding_test.dart
  test/grpc_web_server.dart
  test/grpc_web_test.dart
  test/round_trip_test.dart
  test/server_handles_broken_connection_test.dart
  test/server_test.dart
  test/src/client_utils.dart
  test/src/server_utils.dart
  test/src/utils.dart
  test/timeline_test.dart
  test/timeout_test.dart
Labels: size/L

#443 Spelling fixes
  CHANGELOG.md
  example/grpc-web/README.md
  interop/lib/src/client.dart
Labels: size/S

#442 Update example pubspecs
  example/googleapis/pubspec.yaml
  example/grpc-web/pubspec.yaml
  example/helloworld/pubspec.yaml
  example/metadata/pubspec.yaml
  example/route_guide/pubspec.yaml
  interop/pubspec.yaml
Labels: size/S

#448 Update interop to null-safe grpc-dart
  example/grpc-web/pubspec.yaml
  interop/bin/client.dart
  interop/bin/server.dart
  interop/lib/src/client.dart
  interop/lib/src/generated/empty.pb.dart
  interop/lib/src/generated/messages.pb.dart
  interop/lib/src/generated/messages.pbenum.dart
  interop/lib/src/generated/test.pb.dart
  interop/lib/src/generated/test.pbgrpc.dart
  interop/pubspec.yaml
  pubspec.yaml
Labels: size/L

#441 Move to published, null-safey packages
  example/grpc-web/pubspec.yaml
  pubspec.yaml
Labels: size/S

#449 fix spelling of repository, add missing dev_dependency on pkg:path
  pubspec.yaml
Labels: size/XS

#439 Make status code name as a getter to sync with internal impl
  lib/src/shared/status.dart
Labels: size/M

#450 Bump mockito to breaking change with fixes
  pubspec.yaml
  test/client_tests/client_xhr_transport_test.dart
  test/src/client_utils.mocks.dart
Labels: size/M

#452 Prepare for stable v3 release
  .github/workflows/dart.yml
  CHANGELOG.md
  pubspec.yaml
Labels: size/M
