Repository grpc/grpc-dart, pull requests merged in 2021-08, with the labels that each got.

#504 Reformat code with dev build of dartfmt
  .github/workflows/dart.yml
  example/googleapis/lib/src/generated/google/api/label.pb.dart
  example/googleapis/lib/src/generated/google/api/monitored_resource.pb.dart
  example/googleapis/lib/src/generated/google/logging/type/http_request.pb.dart
  example/googleapis/lib/src/generated/google/logging/v2/log_entry.pb.dart
  example/googleapis/lib/src/generated/google/logging/v2/logging.pb.dart
  example/googleapis/lib/src/generated/google/protobuf/struct.pb.dart
  example/googleapis/lib/src/generated/google/rpc/status.pb.dart
  example/route_guide/lib/src/generated/route_guide.pb.dart
  interop/lib/src/generated/messages.pb.dart
  lib/src/generated/google/rpc/error_details.pb.dart
  lib/src/generated/google/rpc/status.pb.dart
  lib/src/server/handler.dart
Labels: size/XL

#513 Fix interop tests
  interop/bin/client.dart
Labels: size/XS

#493 Add custom trailers to GrpcError
  lib/src/client/call.dart
  lib/src/shared/status.dart
  test/client_tests/client_test.dart
  test/src/client_utils.dart
Labels: size/L

#514 Prepare to release 3.0.1
  CHANGELOG.md
  pubspec.yaml
Labels: size/XS

#516 Fix compilation with DDC
  .github/workflows/dart.yml
  CHANGELOG.md
  lib/src/server/call.dart
  lib/src/server/handler.dart
  lib/src/server/server.dart
  lib/src/shared/io_bits/io_bits.dart
  lib/src/shared/io_bits/io_bits_io.dart
  lib/src/shared/io_bits/io_bits_web.dart
  lib/src/shared/status.dart
  pubspec.yaml
Labels: size/M
