Repository grpc/grpc-dart, pull requests merged in 2021-06, with the labels that each got.

#479 Add GrpcOrGrpcWebClientChannel (#457)
  CHANGELOG.md
  lib/grpc_or_grpcweb.dart
  lib/src/client/grpc_or_grpcweb_channel_grpc.dart
  lib/src/client/grpc_or_grpcweb_channel_web.dart
  test/client_tests/grpc_or_grpcweb_channel_grpc_test.dart
  test/client_tests/grpc_or_grpcweb_channel_web_test.dart
Labels: size/L

#483 GrpcOrGrpcWeb: remove checking if ports are different (#482)
  lib/grpc_or_grpcweb.dart
  lib/src/client/grpc_or_grpcweb_channel_grpc.dart
  lib/src/client/grpc_or_grpcweb_channel_web.dart
  test/client_tests/grpc_or_grpcweb_channel_grpc_test.dart
  test/client_tests/grpc_or_grpcweb_channel_web_test.dart
Labels: size/M

#485 GrpcOrGrpcWeb: provide more flexible constructors (#484)
  lib/grpc_or_grpcweb.dart
  lib/src/client/grpc_or_grpcweb_channel_grpc.dart
  lib/src/client/grpc_or_grpcweb_channel_web.dart
  test/client_tests/grpc_or_grpcweb_channel_grpc_test.dart
  test/client_tests/grpc_or_grpcweb_channel_web_test.dart
Labels: size/L

#492 Fix a typo on the inner invoker parameters
  lib/src/client/client.dart
  test/client_tests/client_interceptor_test.dart
Labels: size/M

#494 Fix interop/bin/server.dart after NNBD migration
  interop/bin/server.dart
Labels: size/XS
