Repository grpc/grpc-dart, pull requests merged in 2021-01, with the labels that each got.

#427 Make sure that grpc_web.dart builds on the Web
  lib/src/client/call.dart
  test/grpc_web_server.dart
Labels: size/M

#433 Create SECURITY.md
  SECURITY.md
Labels: size/XS

#434 Export codecRegistry for connection interface.
  lib/grpc_connection_interface.dart
Labels: size/XS

#435 Fix potential NPE
  lib/src/client/http2_connection.dart
Labels: size/XS

#423 Add XHR raw response to the GrpcError for a better debugging
  lib/src/client/transport/xhr_transport.dart
  lib/src/shared/status.dart
  test/client_tests/client_xhr_transport_test.dart
Labels: size/L

#436 Proper NPE fix
  lib/src/client/http2_connection.dart
Labels: size/XS

#437 Release 2.9.0
  CHANGELOG.md
  pubspec.yaml
Labels: size/S
