Repository grpc/grpc-dart, pull requests merged in 2022-12, with the labels that each got.

#588 Custom Error Handling for Server
  CHANGELOG.md
  example/helloworld/bin/server.dart
  example/helloworld/bin/unix_server.dart
  example/metadata/lib/src/server.dart
  example/route_guide/lib/src/server.dart
  interop/bin/server.dart
  lib/src/server/handler.dart
  lib/src/server/server.dart
  test/client_certificate_test.dart
  test/client_handles_bad_connections_test.dart
  test/grpc_web_server.dart
  test/round_trip_test.dart
  test/server_handles_broken_connection_test.dart
  test/src/server_utils.dart
  test/timeline_test.dart
Labels: size/L

#575 Added ability to set connectTimeout of socket
  CHANGELOG.md
  lib/src/client/http2_connection.dart
  lib/src/client/options.dart
  test/src/client_utils.dart
Labels: size/S

#522 Remove or skip callbacks on old connections
  lib/src/client/http2_connection.dart
Labels: size/S

#590 Expose client IP address to server
  CHANGELOG.md
  lib/src/server/call.dart
  lib/src/server/handler.dart
  lib/src/server/server.dart
  lib/src/shared/io_bits/io_bits_io.dart
  lib/src/shared/io_bits/io_bits_web.dart
  test/src/server_utils.dart
Labels: size/M

#593 Revert "Remove or skip callbacks on old connections"
  lib/src/client/http2_connection.dart
Labels: size/S
