Repository grpc/grpc-dart, pull requests merged in 2023-06, with the labels that each got.

#633 Switch to Dart 3
  .github/workflows/dart.yml
  CHANGELOG.md
  lib/src/client/call.dart
  lib/src/client/channel.dart
  lib/src/client/common.dart
  lib/src/client/transport/web_streams.dart
  lib/src/shared/message.dart
  lib/src/shared/profiler.dart
  lib/src/shared/streams.dart
  pubspec.yaml
  test/timeline_test.dart
  tool/test_all.sh
Labels: size/L

#637 Prepare release of `3.2.0`
  .github/workflows/publish.yaml
  CHANGELOG.md
  pubspec.yaml
Labels: size/S

#629 Bump http version from 0.13.0 to 1.0.0
  CHANGELOG.md
  pubspec.yaml
Labels: size/XS

#641 support latest pkg:protobuf
  .github/workflows/dart.yml
  CHANGELOG.md
  lib/src/client/common.dart
  pubspec.yaml
Labels: size/S

#643 Release v3.2.2
  CHANGELOG.md
  pubspec.yaml
Labels: size/XS

#644 Switch interop tests to Dart 3
  interop/pubspec.yaml
Labels: size/XS

#638 Make constructors of `GrpcError` const
  CHANGELOG.md
  lib/src/shared/status.dart
  pubspec.yaml
Labels: size/M

#634 Keepalive
  CHANGELOG.md
  lib/src/client/client_keepalive.dart
  lib/src/client/http2_connection.dart
  lib/src/client/options.dart
  lib/src/server/handler.dart
  lib/src/server/server.dart
  lib/src/server/server_keepalive.dart
  pubspec.yaml
  test/client_tests/client_keepalive_manager_test.dart
  test/client_tests/client_keepalive_manager_test.mocks.dart
  test/keepalive_test.dart
  test/server_keepalive_manager_test.dart
  test/src/client_utils.dart
  test/src/client_utils.mocks.dart
  test/src/server_utils.dart
Labels: size/XXL

#646 Add permissions to run publish CI
  .github/workflows/publish.yaml
Labels: size/XS

#647 Make `GrpcError` non-final to allow implementations.
  CHANGELOG.md
  lib/src/shared/status.dart
Labels: size/XS

#645 Deflake keepalive tests
  CHANGELOG.md
  lib/src/client/http2_connection.dart
  test/keepalive_test.dart
  test/server_keepalive_manager_test.dart
Labels: size/L
