Repository grpc/grpc-dart, pull requests merged in 2024-09, with the labels that each got.

#724 Use `Map.of` instead of `Map.from` in grpc client.
  CHANGELOG.md
  lib/src/client/call.dart
  lib/src/shared/status.dart
  pubspec.yaml
Labels: size/S

#732 Small fixes
  .github/workflows/dart.yml
  CHANGELOG.md
  README.md
  lib/src/shared/status.dart
  pubspec.yaml
  test/client_tests/client_xhr_transport_test.dart
  test/client_tests/grpc_or_grpcweb_channel_grpc_test.dart
  test/client_tests/grpc_or_grpcweb_channel_web_test.dart
  test/keepalive_test.dart
  test/proxy_secure_test.dart
  test/proxy_test.dart
  test/server_cancellation_test.dart
  test/tools/http2_client.dart
Labels: size/M

#737 ignore unreachable_switch_default in weird switch case
  lib/src/client/transport/web_streams.dart
Labels: size/XS, skip-changelog-check
