Repository grpc/grpc-dart, pull requests merged in 2024-04, with the labels that each got.

#695 Typo Correction in README.md
  example/README.md
Labels: size/XS

#699 Add Health workflow
  .github/workflows/health.yaml
  .github/workflows/post_summaries.yaml
Labels: size/S

#696 Make protobuf generated imports absolute
  .github/workflows/dart.yml
  lib/grpc.dart
  lib/src/shared/status.dart
Labels: size/S

#693 Fix issue 669
  CHANGELOG.md
  lib/src/shared/message.dart
  pubspec.yaml
  test/grpc_compression_flag_test.dart
Labels: size/M
